repos:
-   repo: https://github.com/econchick/interrogate
    rev: 1.7.0
    hooks:
      - id: interrogate
        verbose: True
        exclude: ^(locales|presentation|fuzz/generated|test|cve_bin_tool/checkers|build)
        args: ["-vv", "-i", "-I", "-M", "-C", "-n", "-p", "-f", "60.0"]

-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    - id: isort
      exclude: ^fuzz/generated/

-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.8.0
    hooks:
    - id: black
      exclude: ^fuzz/generated/

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.17.0
    hooks:
    - id: pyupgrade
      exclude: ^fuzz/generated/
      args: ["--py38-plus"]

-   repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
    - id: flake8
      exclude: ^fuzz/generated/|bandit\.conf$

-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.10
    hooks:
    - id: bandit
      exclude: ^fuzz/generated/
      args: ["-c", "bandit.conf"]

-   repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
    - id: gitlint

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
    - id: mypy
      additional_dependencies:
        - types-beautifulsoup4
        - types-jsonschema
        - types-PyYAML
        - types-requests
        - types-setuptools
        - types-toml
      files: |
        (?x)^(
            cve_bin_tool/parsers/.*|
            cve_bin_tool/__init__.py|
            cve_bin_tool/async_utils.py|
            cve_bin_tool/file.py|
            cve_bin_tool/linkify.py|
            cve_bin_tool/log.py|
            cve_bin_tool/strings.py|
            cve_bin_tool/theme.py|
            cve_bin_tool/util.py|
            cve_bin_tool/validator.py|
            cve_bin_tool/version.py|
            doc/.*|
            test/test_data/.*|
            test/__init__.py|
            test/test_file.py|s
            test/test_requirements.py|
            test/test_strings.py|
            test/test_triage.py|
            test/test_version.py|
            test/utils.py|
        )$


