repos:
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    - id: isort

-   repo: https://github.com/python/black
    rev: 22.10.0
    hooks:
    - id: black

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.2.0
    hooks:
    - id: pyupgrade
      args: ["--py37-plus"]

-   repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
    - id: flake8
      exclude: ^fuzz/generated/

-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
    - id: bandit
      args: ["-c", "bandit.conf"]

-   repo: https://github.com/jorisroovers/gitlint
    rev: v0.17.0
    hooks:
    - id: gitlint

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
    - id: mypy
      additional_dependencies:
        - types-beautifulsoup4
        - types-jsonschema
        - types-PyYAML
        - types-requests
        - types-setuptools
        - types-toml
      files: |
        (?x)^(
            cve_bin_tool/parsers/.*|
            cve_bin_tool/__init__.py|
            cve_bin_tool/async_utils.py|
            cve_bin_tool/file.py|
            cve_bin_tool/linkify.py|
            cve_bin_tool/log.py|
            cve_bin_tool/strings.py|
            cve_bin_tool/theme.py|
            cve_bin_tool/util.py|
            cve_bin_tool/validator.py|
            cve_bin_tool/version.py|
            doc/.*|
            test/test_data/.*|
            test/__init__.py|
            test/test_file.py|s
            test/test_requirements.py|
            test/test_strings.py|
            test/test_triage.py|
            test/test_version.py|
            test/utils.py|
        )$
