repos:
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    - id: isort

-   repo: https://github.com/python/black
    rev: 21.11b1
    hooks:
    - id: black

-   repo: https://github.com/asottile/pyupgrade
    rev: v2.29.1
    hooks:
    - id: pyupgrade
      args: ["--py36-plus"]
      
-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    - id: flake8

-   repo: local
    hooks:
    - id: format_checkers
      language: system
      name: format_checkers
      entry: python cve_bin_tool/format_checkers.py
      files: "^cve_bin_tool/checkers/__init__.py"
