repos:
-   repo: https://github.com/pycqa/isort
    rev: 5.6.4
    hooks:
    - id: isort
      args: ["--profile", "black"]

-   repo: https://github.com/python/black
    rev: 20.8b1
    hooks:
    - id: black

-   repo: https://github.com/asottile/pyupgrade
    rev: v2.19.1
    hooks:
    - id: pyupgrade
      args: ["--py36-plus"]

-   repo: local
    hooks: 
    - id: format_checkers
      language: python
      name: format_checkers
      entry: python cve_bin_tool/format_checkers.py
      files: "^cve_bin_tool/checkers/__init__.py"
      types: [python]
