# This is a scheduled workflow to keep a copy of the NVD database

name: Export database

on:
  # schedule:
  #   # Runs at 00:00 UTC every Sunday
  #   - cron: '0 0 * * 0'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  NO_EXIT_CVE_NUM: 1
  nvd_api_key: ${{ secrets.NVD_API_KEY }}

permissions:
  contents: read

jobs:
  update:
    permissions:
      contents: write  # for peter-evans/create-pull-request to create branch
      pull-requests: write  # for peter-evans/create-pull-request to create a PR
    runs-on: ubuntu-22.04

    steps: 
      - name: Harden Runner
        uses: step-security/harden-runner@128a63446a954579617e875aaab7d2978154e969 # v2.4.0
        with:
          egress-policy: audit

      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - uses: actions/setup-python@bd6b4b6205c4dbad673328db7b31b7fab9e241c0 # v4.6.1
        with:
          python-version: '3.x'

      - name: Install cve-bin-tool
        run: |
          python -m pip install --upgrade wheel
          python -m pip install .

      - name: Try single CLI run of tool
        run: |
          NO_EXIT_CVE_NUM=1 python -m cve_bin_tool.cli -u now test/assets/test-kerberos-5-1.15.1.out

      - name: Export database
        run: |
          python -m cve_bin_tool.cli --export-json exported_data

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38 # v5.0.2
        with:
          commit-message: 'chore: update database copy'
          title: 'chore: create copy of NVD database'
          branch: chore-update_database-copy
          base: mirror
          delete-branch: true
          author: GitHub <noreply@github.com>
