name: Formatting

on:
  push:
    branches:
      - main
    paths:
      - 'cve_bin_tool/checkers/__init__.py'

jobs:
  formatting:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
      - name: Install cve-bin-tool
        run: |
          python -m pip install --upgrade wheel
          python -m pip install .
      - name: Run format_checkers.py
        run: |
          python cve_bin_tool/format_checkers.py
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "chore: update checkers table"
          title: "chore: update checkers table"
          branch: chore-update-table
          delete-branch: true
          author: GitHub <noreply@github.com>
