name: Update checkers table

on:
  push:
    branches:
      - main
    paths:
      - 'cve_bin_tool/checkers/__init__.py'

permissions:
  contents: read

jobs:
  formatting:
    permissions:
      contents: write  # for peter-evans/create-pull-request to create branch
      pull-requests: write  # for peter-evans/create-pull-request to create a PR
    name: Update checkers table
    runs-on: ubuntu-22.04
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install cve-bin-tool
        run: |
          python -m pip install --upgrade wheel
          python -m pip install .
      - name: Run format_checkers.py
        run: |
          python cve_bin_tool/format_checkers.py
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38 # v5.0.2
        with:
          commit-message: "chore: update checkers table"
          title: "chore: update checkers table"
          branch: chore-update-table
          delete-branch: true
          author: GitHub <noreply@github.com>
