name: Update checkers table

on:
  push:
    branches:
      - main
    paths:
      - 'cve_bin_tool/checkers/__init__.py'

permissions:
  contents: read

jobs:
  formatting:
    permissions:
      contents: write  # for peter-evans/create-pull-request to create branch
      pull-requests: write  # for peter-evans/create-pull-request to create a PR
    name: Update checkers table
    runs-on: ubuntu-22.04
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0d381219ddf674d61a7572ddd19d7941e271515c # v2.9.0
        with:
          egress-policy: audit

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f # v5.1.1
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install cve-bin-tool
        run: |
          python -m pip install --upgrade wheel
          python -m pip install .
      - name: Run format_checkers.py
        run: |
          python cve_bin_tool/format_checkers.py
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@c5a7806660adbe173f04e3e038b0ccdcd758773c # v6.1.0
        with:
          commit-message: "chore: update checkers table"
          title: "chore: update checkers table"
          branch: chore-update-table
          delete-branch: true
          author: GitHub <noreply@github.com>
