name: Update cached database

on:
  schedule:
    # Runs at 00:20 UTC everyday
    - cron: '20 0 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  NO_EXIT_CVE_NUM: 1
  nvd_api_key: ${{ secrets.NVD_API_KEY }}

permissions:
  contents: read

jobs:
  linux:
    if: github.repository == 'intel/cve-bin-tool'
    name: Update linux cached database
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Get date
        id: get-date
        run: |
          echo "date=$(/bin/date -u "+%Y%m%d")" >> $GITHUB_OUTPUT
      - uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: cache
          key: Linux-cve-bin-tool-${{ steps.get-date.outputs.date }}
      - name: Install cve-bin-tool
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools
          python -m pip install --upgrade wheel
          python -m pip install --editable .
      - name: Update database
        run: |
          [[ -e cache ]] && mkdir -p .cache && mv cache ~/.cache/cve-bin-tool
          python -m cve_bin_tool.cli test/assets/test-kerberos-5-1.15.1.out -u now
          cp -r ~/.cache/cve-bin-tool cache

# Windows cache is currently disabled.
