name: Update cached database

on:
  schedule:
    # Runs at 00:20 UTC everyday
    - cron: '20 0 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  NO_EXIT_CVE_NUM: 1
  nvd_api_key: ${{ secrets.NVD_API_KEY }}

permissions:
  contents: read

jobs:
  linux:
    if: github.repository == 'intel/cve-bin-tool'
    name: Update linux cached database
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@128a63446a954579617e875aaab7d2978154e969 # v2.4.0
        with:
          egress-policy: audit

      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: actions/setup-python@bd6b4b6205c4dbad673328db7b31b7fab9e241c0 # v4.6.1
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Get date
        id: get-date
        run: |
          echo "date=$(/bin/date -u "+%Y%m%d")" >> $GITHUB_OUTPUT
      - uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        with:
          path: cache
          key: Linux-cve-bin-tool-${{ steps.get-date.outputs.date }}
      - name: Install cve-bin-tool
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools
          python -m pip install --upgrade wheel
          python -m pip install --editable .
      - name: Update database
        run: |
          [[ -e cache ]] && mkdir -p .cache && mv cache ~/.cache/cve-bin-tool
          python -m cve_bin_tool.cli test/assets/test-kerberos-5-1.15.1.out -u now
          cp -r ~/.cache/cve-bin-tool cache

# Windows cache is currently disabled.
