# This is a scheduled workflow to keep the spdx header up to date

name: Update spdx header

on:
  schedule:
    # Runs at 00:00 UTC on the 2nd January of every year
    - cron: '0 0 2 1 *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update:
    permissions:
      contents: write  # for peter-evans/create-pull-request to create branch
      pull-requests: write  # for peter-evans/create-pull-request to create a PR
    name: Update spdx header
    runs-on: ubuntu-20.04

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Update spdx header
        run: |
          sed -i "s/[0-9]\{4\}/$(date +%Y)/" spdx_header.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@b1ddad2c994a25fbc81a28b3ec0e368bb2021c50 # v6.0.0
        with:
          commit-message: 'chore: update spdx header'
          title: 'chore: update spdx header'
          branch: chore-spdx-header
          delete-branch: true
          author: GitHub <noreply@github.com>
