name: Update cached database

on:
  schedule:
    # Runs at 00:20 UTC everyday
    - cron: '20 0 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  NO_EXIT_CVE_NUM: 1
  nvd_api_key: ${{ secrets.NVD_API_KEY }}

jobs:
  linux:
    if: github.repository == 'intel/cve-bin-tool'
    name: Update linux cached database
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Get date
        id: get-date
        run: |
          echo "date=$(/bin/date -u "+%Y%m%d")" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        with:
          path: ~/.cache/cve-bin-tool
          key: ${{ runner.os }}-cve-bin-tool-${{ steps.get-date.outputs.date }}
      - name: Install cve-bin-tool
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools
          python -m pip install --upgrade wheel
          python -m pip install --editable .
      - name: Update database
        run: |
          python -m cve_bin_tool.cli test/assets/test-kerberos-5-1.15.1.out -u now

  windows:
    if: github.repository == 'intel/cve-bin-tool'
    name: Update windows cached database
    runs-on: windows-latest
    timeout-minutes: 20
    env:
      PYTHONIOENCODING: 'utf8'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Get date
        id: get-date
        run: |
          echo "date=$(get-date -format "yyyyMMdd")" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        with:
          path: ~/.cache/cve-bin-tool
          key: ${{ runner.os }}-cve-bin-tool-${{ steps.get-date.outputs.date }}
      - name: Install cve-bin-tool
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools
          python -m pip install --upgrade wheel
          python -m pip install --upgrade .
      - name: Try single CLI run of tool
        run: |
          python -m cve_bin_tool.cli test/assets/test-kerberos-5-1.15.1.out -u now
