# This is a scheduled workflow to keep the spdx header up to date

name: Update spdx header

on:
  schedule:
    # Runs at 00:00 UTC on the 2nd January of every year
    - cron: '0 0 2 1 *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update:
    name: Update spdx header
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Update spdx header
        run: |
          sed -i "s/[0-9]\{4\}/$(date +%Y)/" spdx_header.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: 'chore: update spdx header'
          title: 'chore: update spdx header'
          branch: chore-spdx-header
          delete-branch: true
          author: GitHub <noreply@github.com>
